import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../stage-large-project-store.js',import.meta.url),'utf8');
const context={queueMicrotask};vm.runInNewContext(source,context);const api=context.STAGE_LARGE_PROJECT_STORE;
const [current,shelf]=api.KEYS;
class Storage {constructor(values={}){this.map=new Map(Object.entries(values));this.access=[];}getItem(k){this.access.push(k);return this.map.get(k)??null;}setItem(k,v){this.access.push(k);this.map.set(k,String(v));}removeItem(k){this.access.push(k);this.map.delete(k);}}
function repo(){const rows=new Map();return {rows,fail:null,async read(){return structuredClone(rows.get('current')??null);},async initialize(values){if(!rows.has('current')){const p={version:1,revision:0,values:{...values}};rows.set('current',p);rows.set('migration',structuredClone(p));}return this.read();},async commit(revision,values){if(this.fail)throw this.fail;const before=rows.get('current');if(!api.pairValid(before)||before.revision!==revision)return null;const next={version:1,revision:revision+1,values:{...values}};rows.set('previous',structuredClone(before));rows.set('current',next);return structuredClone(next);},async records(){return [...rows].map(([copy,p])=>({...structuredClone(p),copy}));},async clear(){rows.clear();}};}
const values=()=>({[current]:'{"project":{"id":"test"},"unknown":"retain"}',[shelf]:'{"other":{"state":{"project":{"id":"other"}}}}'});
test('verified migration retains exact source and never accesses Beta keys',async()=>{const originals=values(),storage=new Storage({...originals,'shosai-stage-sketch-v1':'beta'}),r=repo();const a=await api.open({storage,repo:r});assert.deepEqual({...a.values()},originals);assert.deepEqual(r.rows.get('migration').values,originals);assert.equal(storage.map.get('shosai-stage-sketch-v1'),'beta');assert.equal(storage.access.includes('shosai-stage-sketch-v1'),false);assert.equal(storage.getItem(current),null);});
test('50 MiB pair is durable, reopens intact and retains previous generation',async()=>{const storage=new Storage(),r=repo(),a=await api.open({storage,repo:r});const payload='x'.repeat(25*1024*1024);a.storage.setItem(current,payload);a.storage.setItem(shelf,payload);await a.flush();assert.equal(a.status().revision,1);const b=await api.open({storage,repo:r});assert.equal(b.storage.getItem(current),payload);assert.equal(b.storage.getItem(shelf),payload);assert.equal(r.rows.get('previous').values[current],null);assert.equal(storage.getItem(current),null);});
test('stale tab cannot overwrite a newer atomic pair',async()=>{const storage=new Storage(values()),r=repo(),a=await api.open({storage,repo:r}),b=await api.open({storage,repo:r});a.storage.setItem(current,'newer');await a.flush();b.storage.setItem(current,'stale');await assert.rejects(b.flush(),e=>e.code==='CONCURRENT_EDIT');assert.equal((await r.read()).values[current],'newer');});
test('quota failure retains committed pair and reports failure',async()=>{const originals=values(),storage=new Storage(originals),r=repo();let failure;const a=await api.open({storage,repo:r,onFailure:e=>failure=e});r.fail=Object.assign(Error('quota'),{name:'QuotaExceededError'});a.storage.setItem(current,'unsaved');await assert.rejects(a.flush(),{name:'QuotaExceededError'});assert.equal(failure.name,'QuotaExceededError');assert.deepEqual((await r.read()).values,originals);assert.equal(a.values()[current],'unsaved');});
test('interrupted migration retries only matching revision zero sources',async()=>{const originals=values(),r=repo();await r.initialize(originals);const storage=new Storage({[shelf]:originals[shelf]});await api.open({storage,repo:r});assert.equal(storage.getItem(shelf),null);storage.setItem(current,'old tab changed');await assert.rejects(api.open({storage,repo:r}),e=>e.code==='LEGACY_WRITE_CONFLICT');assert.equal(storage.getItem(current),'old tab changed');});
test('missing or corrupt primary halts without overwriting sources',async()=>{const storage=new Storage({[api.MARKER]:'2'}),r=repo();await assert.rejects(api.open({storage,repo:r}),e=>e.code==='PRIMARY_MISSING');r.rows.set('current',{version:1,revision:2});await assert.rejects(api.open({storage,repo:r}),e=>e.code==='PRIMARY_CORRUPT');assert.equal(r.rows.get('current').revision,2);});
test('old client writes during edit block the commit and preserve both originals',async()=>{const storage=new Storage(values()),r=repo(),a=await api.open({storage,repo:r});storage.setItem(current,'old client');a.storage.setItem(shelf,'new shelf');await assert.rejects(a.flush(),e=>e.code==='LEGACY_WRITE_CONFLICT');assert.equal((await r.read()).values[shelf],values()[shelf]);assert.equal(storage.getItem(current),'old client');});
test('explicit reset clears all primary generations and marker, preserves settings and Beta',async()=>{const storage=new Storage({...values(),setting:'keep',beta:'keep'}),r=repo(),a=await api.open({storage,repo:r});await a.reset();assert.equal(r.rows.size,0);assert.equal(storage.getItem(api.MARKER),null);assert.equal(storage.getItem('setting'),'keep');assert.equal(storage.getItem('beta'),'keep');});

vm.runInNewContext(fs.readFileSync(new URL('../stage-storage-hygiene.js',import.meta.url),'utf8'),context);
test('audio referenced only by migration or previous copies stays protected',async()=>{const storage=new Storage({[current]:JSON.stringify({project:{audioTracks:[{id:'migration-audio'}]}}),[shelf]:'{}'}),r=repo(),a=await api.open({storage,repo:r});a.storage.setItem(current,JSON.stringify({project:{audioTracks:[{id:'previous-audio'}]}}));await a.flush();a.storage.setItem(current,JSON.stringify({project:{audioTracks:[{id:'current-audio'}]}}));await a.flush();assert.deepEqual([...await a.protectedAudioIds()].sort(),['current-audio','migration-audio','previous-audio']);});

test('migration at the old quota boundary frees only verified sources before retrying the marker',async()=>{const original=values(),storage=new Storage(original),r=repo();const set=storage.setItem.bind(storage);storage.setItem=(k,v)=>{if(k===api.MARKER&&storage.getItem(current)!==null)throw Object.assign(Error('full'),{name:'QuotaExceededError'});set(k,v);};const a=await api.open({storage,repo:r});assert.deepEqual({...a.values()},original);assert.deepEqual(r.rows.get('migration').values,original);assert.equal(storage.getItem(api.MARKER),'0');});
