"use strict";
window.ROSDistributionUI={create({read,apply,persist,finish,report,basis,language=()=>"ja"}){
  const D=window.ROSDistribution,T=window.ROSTiming,dialog=document.getElementById('distribution-dialog'),$=id=>dialog.querySelector('#'+id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readable=v=>Array.isArray(v)?v.map(x=>Array.isArray(x)?x.join('：'):x.caption||x.assetId||String(x)).join('\n'):v===null?'未定':String(v??'');
  const history=()=>read().distributions||{version:1,releases:[]};
  let busy=false,returnFocus=null;
  function message(value,error=false){$('distribution-status').textContent=value;$('distribution-status').classList.toggle('distribution-error',error);}
  function setBusy(value){busy=value;for(const node of dialog.querySelectorAll('button,input,textarea,select'))node.disabled=value;dialog.setAttribute('aria-busy',String(value));}
  function download(value,type,name){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function selected(h=history()){return h.releases.find(r=>r.id===$('distribution-version').value);}
  function showChanges(host,list){host.replaceChildren();if(!list.length){host.textContent='前の配布版から変更はありません。';return;}for(const c of list){const li=document.createElement('li'),heading=document.createElement('strong');heading.textContent=c.kind+'：'+c.title;li.append(heading);for(const delta of c.deltas){const p=document.createElement('p');p.className='small';p.textContent=delta.label+'：'+readable(delta.before)+' → '+readable(delta.after);li.append(p);}host.append(li);}}
  function render(){
    const h=history(),keep=$('distribution-version').value,versions=$('distribution-version');versions.replaceChildren();
    for(const r of [...h.releases].reverse()){const option=document.createElement('option');option.value=r.id;option.textContent=r.label+' · '+T.dateText(r.createdAt,language(),{time:true,seconds:true});versions.append(option);}if(h.releases.some(r=>r.id===keep))versions.value=keep;
    const r=selected(h),previous=r&&h.releases.find(p=>p.id===r.previousId),latest=h.releases.at(-1);
    $('distribution-existing').hidden=!r;$('distribution-empty').hidden=!!r;
    showChanges($('distribution-draft-changes'),D.changes(latest?.document,D.publicDocument(read(),$('distribution-notes').checked)));
    if(!r)return;
    $('distribution-version-note').textContent=r===latest?'このショーで最後に作った配布版です。編集内容とは別に固定されています。':'過去の配布版です。この版への返答は最新の配布版の確認にはなりません。';
    showChanges($('distribution-changes'),D.changes(previous?.document,r.document));
    const body=$('distribution-replies');body.replaceChildren();
    for(const target of r.targets){const reply=D.status(r,target),tr=document.createElement('tr');for(const text of [target,reply.label,reply.name||'—',reply.message||'—']){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);}
  }
  // 2026-10-07 G1 #1: the distributed HTML is written in the paper language of this device (ja / en / bilingual = both).
  const VIEW_TEXT={runOfShow:['進行表','Run of show'],release:['配布版：','Release: ','配布版 Release：'],fixed:['固定した版 / 自動更新されません','Fixed release · not updated automatically','固定した版 / 自動更新されません · Fixed release, not updated automatically'],
    start:['開始 ','Start '],undecided:['未定','TBD'],created:['作成 ','Created ','作成 Created '],releaseId:['版ID ','Release ID ','版ID Release ID '],
    intro:['シーンと転換の進行一覧です。予定時刻は実行命令ではありません。キュー専用行・合図詳記の個別編集・生成した舞台図は含みません。','Running order of scenes and transitions. Planned times are not execution commands. Cue rows, calling-sheet edits and generated stage diagrams are not included.','シーンと転換の進行一覧です。予定時刻は実行命令ではありません。キュー専用行・合図詳記の個別編集・生成した舞台図は含みません。 / Running order of scenes and transitions. Planned times are not execution commands.'],
    changes:['前の配布版からの変更（{0}件）','Changes since the previous release ({0})','前の配布版からの変更 Changes（{0}）'],
    headings:[['番号','予定','尺','項目・担当','STBY / GO','各部の指示','詳細','備考'],['No.','Start','Dur.','Item / Who','STBY / GO','Departments','Details','Notes']],
    transition:['転換','Transition','転換 Transition'],review:['（要確認）',' (check)'],
    replyHeading:['この版への返答','Reply to this release','この版への返答 Reply'],replyIntro:['読んだ届け先と名前を記入し、返答ファイルを作成者へ送ってください。本人認証はありません。ここでの操作だけでは返答は届きません。','Choose the recipient, enter your name and send the reply file to the author. There is no identity check. Nothing is sent from this page.'],
    target:['届け先','Recipient','届け先 Recipient'],choose:['選んでください','Choose'],name:['名前','Name','名前 Name'],status:['返答','Reply','返答 Reply'],confirmed:['この版を確認しました','I have read this release','この版を確認しました / I have read this release'],question:['質問があります','I have a question','質問があります / I have a question'],
    message:['連絡・質問','Message / question','連絡・質問 Message'],save:['返答ファイルを保存','Save the reply file','返答ファイルを保存 / Save the reply file'],
    footer:['このファイルは配布版の写しです。最新版は作成者に確認してください。印刷・PDFはブラウザの印刷機能を使えます。','This file is a copy of the release. Ask the author for the latest version. Use the browser to print or save a PDF.'],
    invalid:['名前と質問内容を確認してください。','Check your name and your question.','名前と質問内容を確認してください。 / Check your name and your question.'],saved:['返答ファイルを保存しました。作成者へファイルを送ってください。','Reply file saved. Send the file to the author.','返答ファイルを保存しました。作成者へファイルを送ってください。 / Reply file saved. Send it to the author.']};
  const KIND_EN={'追加':'Added','変更':'Changed','削除':'Removed'},FIELD_EN={title:'Item',hold:'Duration',transition:'Transition',owner:'Who',standby:'STBY',go:'GO',dept:'Departments',details:'Details',notes:'Notes',transitionDetail:'Transition details',transitionNotes:'Transition notes',detailAssets:'Detail images',noteAssets:'Note images',order:'Order',venue:'Venue',date:'Date',startTime:'Start time'};
  function viewText(lang,key,...args){const e=VIEW_TEXT[key],v=lang==='en'?e[1]:lang==='bilingual'?(e[2]??e[0]):e[0];return typeof v==='string'?v.replace(/\{(\d)\}/g,(_,i)=>String(args[Number(i)]??'')):v;}
  // 2026-10-07 G1 (本人決定): the covering message follows the paper language too. English → English; Japanese and the
  // bilingual paper → the Japanese message (bilingual keeps values and generated sentences in Japanese).
  function coverMessage(r){
    const title=String(r.document.documentInfo.title??'');
    if(language()==='en')return (title?title+' — ':'')+'run of show '+r.label+'\nRelease ID: '+r.id+'\nRecipients: '+r.targets.join(', ')+'\nPlease check the changes and the running order in the attached HTML, and send back the reply file to confirm or to ask a question.';
    return readable(r.document.documentInfo.title)+' の進行表 '+r.label+' をお送りします。\n版ID：'+r.id+'\n届け先：'+r.targets.join('、')+'\n添付のHTMLで変更点と進行を確認し、確認・質問の返答ファイルを返信してください。';
  }
  function images(refs,assets){return refs.map(ref=>{const a=assets.find(a=>a.id===ref.assetId);return a?'<figure><img src="'+esc(a.dataUrl)+'" alt="'+esc(ref.caption||a.name)+'"><figcaption>'+esc(ref.caption)+'</figcaption></figure>':'';}).join('');}
  function viewer(r){
    const h=history(),previous=h.releases.find(p=>p.id===r.previousId),changes=D.recipientChanges(previous,r),d=r.document,flow=T.timeline(d.items,d.documentInfo.startTime);
    const lang=['ja','en','bilingual'].includes(language())?language():'ja',V=(key,...args)=>viewText(lang,key,...args),en=lang==='en';
    const value=v=>en&&v===null?'TBD':en&&Array.isArray(v)?v.map(x=>Array.isArray(x)?x.join(': '):x.caption||x.assetId||String(x)).join('\n'):readable(v);
    const kind=c=>en?KIND_EN[c.kind]||c.kind:c.kind,title=c=>en&&c.id.startsWith('info-')?FIELD_EN[c.id.slice(5)]||c.title:c.title,label=delta=>en?FIELD_EN[delta.key]||delta.label:delta.label,colon=en?': ':'：';
    const rows=d.items.map((i,n)=>'<tr><td>'+String(n+1)+'</td><td>'+esc(T.formatClock(flow[n].start,lang))+'</td><td>'+esc(T.formatDuration(i.hold,lang))+'</td><td><strong>'+esc(i.title)+'</strong><br>'+esc(i.owner)+'</td><td>STBY'+colon+esc(i.standby)+'<br>GO'+colon+esc(i.go)+'</td><td class="pre">'+esc(value(i.dept))+'</td><td class="pre">'+esc(i.details)+images(i.detailAssets,d.assets)+'</td><td class="pre">'+esc(i.notes)+images(i.noteAssets,d.assets)+'</td></tr><tr class="transition"><td></td><td>'+esc(T.formatClock(flow[n].after,lang))+'</td><td>'+esc(T.formatDuration(i.transition,lang))+'</td><td>'+esc(V('transition'))+(i.transitionReview?esc(V('review')):'')+'</td><td colspan="3" class="pre">'+esc(i.transitionDetail)+'</td><td class="pre">'+esc(i.transitionNotes)+'</td></tr>').join('');
    const changeHTML=changes.map(c=>'<li><strong>'+esc(kind(c)+colon+title(c))+'</strong>'+c.deltas.map(delta=>'<p class="pre">'+esc(label(delta)+colon+value(delta.before)+' → '+value(delta.after))+'</p>').join('')+'</li>').join('');
    const heads=lang==='bilingual'?VIEW_TEXT.headings[0].map((ja,k)=>ja===VIEW_TEXT.headings[1][k]?ja:ja+' / '+VIEW_TEXT.headings[1][k]):VIEW_TEXT.headings[en?1:0];
    const meta={format:D.FORMAT,version:1,releaseId:r.id,hash:r.hash,targets:r.targets,label:r.label,text:{invalid:V('invalid'),saved:V('saved')}};
    const js='('+receiver.toString()+')('+JSON.stringify(meta).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')+');';
    return '<!doctype html><html lang="'+(en?'en':'ja')+'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'; script-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+esc(d.documentInfo.title+' · '+r.label)+'</title><style>'+viewerStyle()+'</style><main><header><h1>'+esc(d.documentInfo.title||V('runOfShow'))+'</h1><p><strong>'+esc(V('release'))+esc(r.label)+'</strong> · '+esc(V('fixed'))+'</p><p>'+esc([d.documentInfo.venue,d.documentInfo.date?T.dateText(d.documentInfo.date,lang):"",V('start')+T.formatClock(T.startSeconds(d.documentInfo.startTime),lang)].filter(Boolean).join(' · '))+' · Asia/Tokyo</p><p>'+esc(V('created'))+esc(T.dateText(r.createdAt,lang,{time:true,seconds:true}))+' · '+esc(V('releaseId'))+esc(r.id)+'</p></header><p>'+esc(V('intro'))+'</p><details><summary>'+esc(V('changes',changes.length))+'</summary><ul>'+changeHTML+'</ul></details><div class="table-wrap"><table><thead><tr>'+heads.map(v=>'<th>'+esc(v)+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div><section><h2>'+esc(V('replyHeading'))+'</h2><p>'+esc(V('replyIntro'))+'</p><form id="reply-form"><label>'+esc(V('target'))+'<select id="reply-target" required><option value="">'+esc(V('choose'))+'</option>'+r.targets.map(t=>'<option>'+esc(t)+'</option>').join('')+'</select></label><label>'+esc(V('name'))+'<input id="reply-name" required maxlength="100" autocomplete="name"></label><label>'+esc(V('status'))+'<select id="reply-status"><option value="confirmed">'+esc(V('confirmed'))+'</option><option value="question">'+esc(V('question'))+'</option></select></label><label>'+esc(V('message'))+'<textarea id="reply-message" maxlength="4000"></textarea></label><button type="submit">'+esc(V('save'))+'</button><p id="reply-result" role="status"></p></form></section><footer>'+esc(V('footer'))+'</footer></main><script>'+js+'</script></html>';
  }
  function receiver(meta){
    const form=document.getElementById('reply-form'),result=document.getElementById('reply-result'),message=document.getElementById('reply-message');
    document.getElementById('reply-status').addEventListener('change',e=>{message.required=e.target.value==='question';});
    form.addEventListener('submit',event=>{event.preventDefault();const name=document.getElementById('reply-name').value.trim(),text=message.value.trim(),status=document.getElementById('reply-status').value;
      if(!name||(status==='question'&&!text)){result.textContent=meta.text?.invalid||'名前と質問内容を確認してください。';return;}
      const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);const id='reply-'+[...bytes].map(v=>v.toString(16).padStart(2,'0')).join('');
      const reply={format:meta.format,version:meta.version,id,releaseId:meta.releaseId,hash:meta.hash,target:document.getElementById('reply-target').value,name,status,message:text,createdAt:new Date().toISOString()};
      const url=URL.createObjectURL(new Blob([JSON.stringify(reply,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=meta.releaseId+'-reply.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);result.textContent=meta.text?.saved||'返答ファイルを保存しました。作成者へファイルを送ってください。';
    });
  }
  function viewerStyle(){return '*,*::before,*::after{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#25352f;font:16px/1.6 system-ui,-apple-system,"Hiragino Sans",sans-serif}main{max-width:1440px;margin:auto;padding:24px}h1{font-size:28px}h2{font-size:24px}header{border-bottom:3px solid #245540}p{overflow-wrap:anywhere}.table-wrap{overflow:auto;background:#fff}table{width:100%;min-width:1080px;border-collapse:collapse}th,td{padding:8px;border:1px solid #79877e;text-align:left;vertical-align:top}th{background:#edf3ee}.pre{white-space:pre-wrap}.transition{background:#edf3ee}img{max-width:200px;height:auto}figure{margin:8px 0}section{margin-top:32px}label{display:block;max-width:560px;margin-bottom:16px}input,select,textarea,button,summary{font:inherit;min-height:44px}input,select,textarea{display:block;width:100%;padding:8px;border:1px solid #79877e;background:#fff;color:#25352f}textarea{min-height:120px}button{background:#245540;color:white;border:0;padding:8px 16px;cursor:pointer}summary{cursor:pointer}footer{margin-top:32px;color:#52625a}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid #842e3b;outline-offset:4px}@media print{body{background:#fff}main{padding:0}section,details{display:none}.table-wrap{overflow:visible}table{min-width:0;font-size:10pt}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4 landscape;margin:10mm}}';}
  async function action(fn){if(busy)return;setBusy(true);try{await fn();}catch(error){message(error.message,true);report?.(error);}finally{setBusy(false);render();}}
  $('distribution-create').addEventListener('click',()=>action(async()=>{
    const guard=basis(),doc=read(),recipients=D.targets($('distribution-targets').value),r=await D.create(doc,{label:$('distribution-label').value,targets:recipients,includeNotes:$('distribution-notes').checked,history:history()});
    doc.distributions={version:1,releases:[...history().releases,r]};await apply(doc,guard);$('distribution-version').value=r.id;message('配布版をショーへ保存しました。HTMLを渡して配布してください。');
  }));
  $('distribution-download').addEventListener('click',()=>action(async()=>{const r=selected();if(!r)return;await persist();if(await D.hash(r)!==r.hash)throw Error('配布版の内容と記録が一致しません。');download(viewer(r),'text/html',r.id+'.html');message('固定したHTMLを保存しました。届け先へこのファイルを渡してください。');}));
  $('distribution-copy').addEventListener('click',()=>action(async()=>{const r=selected();if(!r)return;await persist();const text=coverMessage(r);$('distribution-message').value=text;$('distribution-message').hidden=false;$('distribution-message').focus();$('distribution-message').select();try{await navigator.clipboard.writeText(text);message('連絡文をコピーしました。HTMLを添付して送ってください。');}catch{message('連絡文を表示しました。選択してコピーできます。');}}));
  $('distribution-reply-file').addEventListener('change',event=>action(async()=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>32768)throw Error('返答ファイルは32 KiB以内で読み込んでください。');const guard=basis(),doc=read(),input=JSON.parse(await file.text()),h=await D.addReply(doc.distributions||{version:1,releases:[]},input);doc.distributions=h;await apply(doc,guard);$('distribution-version').value=input.releaseId;message('返答を '+h.releases.find(r=>r.id===input.releaseId).label+' へ取り込みました。本人認証は行っていません。');}));
  $('distribution-version').addEventListener('change',()=>{render();message('選択した配布版の内容と返答を表示しています。');});$('distribution-notes').addEventListener('change',render);
  $('distribution-reply-pick').addEventListener('click',()=>$('distribution-reply-file').click());
  $('distribution-close').addEventListener('click',()=>{if(!busy)dialog.close();});dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>returnFocus?.focus());
  return {open(){if(!finish())return;returnFocus=document.activeElement;const doc=read(),h=history();$('distribution-label').value='配布 '+String(h.releases.length+1).padStart(2,'0');$('distribution-targets').value=h.releases.at(-1)?.targets.join('\n')||[...new Set(['舞台監督',...doc.items.flatMap(i=>i.dept.map(d=>d[0]))])].join('\n');$('distribution-notes').checked=false;message('固定する内容と届け先を確認してください。備考は初期状態では含めません。');render();dialog.showModal();$('distribution-label').focus();}};
}};
