'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'); const path=require('node:path');
const h=require('./browser-helpers.cjs');
const fixtures=[['ft-scene-a5','ft-cast-p01','A-5','演者01'],['ft-scene-c1','ft-set-bar-counter','C-1','バーカウンター']];
async function selection(page,view) {
  const checks=[];
  for(const on of [true,false]){await h.floating(page,on);for(const li of [0,1,2,3]){await h.layout(page,li);for(const [scene,id,label,name] of fixtures){
    await h.selectPlan(page,scene,id); const plan=await h.inspector(page); assert.equal(plan.floating,on,'Plan inspector must reflect the requested floating preference'); assert(plan.name.includes(name),`Wrong selection: ${plan.name}`);
    if(view==='front'){await h.selectFront(page); const front=await h.inspector(page);assert.equal(front.floating,on,'Front inspector must reflect the requested floating preference');assert.equal(front.name,plan.name,'Front canvas must select the same piece');checks.push({scene:label,id,on,layout:li,view,...front});}
    else checks.push({scene:label,id,on,layout:li,view,...plan});
    const getLock=async()=>{const p=await h.assertFixture(page);return !!(id.startsWith('ft-set-')?p.sets:p.cast).find(x=>x.id===id).locked;};
    const locked=await getLock();await page.locator('#stage-piece-lock').click();assert.equal(await getLock(),!locked,'Reachable inspector lock control must change the fixture');await page.locator('#stage-piece-lock').click();assert.equal(await getLock(),locked,'Lock control must restore the fixture');
  }}}
  await h.floating(page,true);await h.layout(page,0);return {checks,scene:'A-5 / C-1',assertions:checks.length};
}
async function laneCase(page,key) {
  await h.assertFixture(page); await h.layout(page,key==='right2'?1:0); const before=await h.lane(page,key);
  if(!before.visible){assert(page.viewportSize().width<1366,'Expected desktop lane unexpectedly hidden');assert(before.max===0||page.viewportSize().width<1100,'Expected desktop lane unexpectedly hidden');return{status:'na',reason:'CSS layout at this viewport has no resizable lane',key,before};}
  assert(before.reachable&&!before.overlap,`Lane handle unreachable or over panel: ${JSON.stringify(before)}`);
  if(before.max<=before.min){assert(page.viewportSize().width<1366,'Expected desktop lane has no resize range');return{status:'na',reason:'Viewport leaves no lane-width adjustment range',key,before};}
  const grow=before.max-before.value,shrink=before.value-before.min;const delta=grow>=shrink?Math.min(40,grow):-Math.min(40,shrink);assert(Math.abs(delta)>=1,'Resizable lane must allow a measurable change');
  await page.mouse.move(before.x,before.y);await page.mouse.down();await page.mouse.move(before.x+delta*(key==='left'?1:-1),before.y,{steps:8});await page.mouse.up();await h.settle(page);
  const dragged=await h.lane(page,key);assert.equal(dragged.value,before.value+delta,'Pointer drag must change actual width');assert(Math.abs(dragged.width-dragged.value)<2,'Host width must match saved width');
  const handle=page.locator(`.stage-panel-width-handle[data-panel-width="${key}"]`);await handle.focus(); const arrow=delta>0?(key==='left'?'ArrowRight':'ArrowLeft'):(key==='left'?'ArrowLeft':'ArrowRight');await page.keyboard.press(arrow);await h.settle(page);
  const keyboard=await h.lane(page,key);assert.equal(keyboard.value,Math.max(keyboard.min,Math.min(keyboard.max,dragged.value+(delta>0?10:-10))),'Keyboard must adjust width within viewport limits');
  await h.reloadFixture(page);const reloaded=await h.lane(page,key);assert.equal(reloaded.value,keyboard.value,'Lane width must persist across reload');assert(Math.abs(reloaded.width-reloaded.value)<2,'Reloaded host width must match preference');
  await handle.focus();await page.keyboard.press('Enter');await h.settle(page);const reset=await h.lane(page,key);assert.equal(reset.value,before.value,'Enter must restore default width');
  return{scene:'C-1',key,before,dragged,keyboard,reloaded,reset};
}
async function storageRoundtrip({page,outputDir}) {
  assert(outputDir,'Runner must supply outputDir');await h.selectPlan(page,'ft-scene-c1','ft-set-bar-counter');await h.inspector(page);const initial=await h.assertFixture(page); const initialLock=!!initial.sets.find(x=>x.id==='ft-set-bar-counter').locked;
  await page.locator('#stage-piece-lock').click();const changed=await h.assertFixture(page);assert.equal(!!changed.sets.find(x=>x.id==='ft-set-bar-counter').locked,!initialLock);
  await h.reloadFixture(page);const persisted=await h.assertFixture(page);assert.equal(!!persisted.sets.find(x=>x.id==='ft-set-bar-counter').locked,!initialLock,'C-1 UI edit must survive reload');
  // Headless browser cannot operate the OS save picker; exercise the supported download transport.
  await page.evaluate(()=>{window.showSaveFilePicker=undefined;});
  await page.locator('#stage-export-json').scrollIntoViewIfNeeded();await page.locator('#stage-export-json').click();await page.locator('#stage-project-export-modal').waitFor({state:'visible'});const downloaded=page.waitForEvent('download');await page.locator('#stage-project-export-form button[type=submit]').click();if(await page.locator('#stage-venue-export-include').isVisible())await page.locator('#stage-venue-export-include').click();const download=await downloaded;await fs.mkdir(outputDir,{recursive:true});const file=path.join(outputDir,'fixture-roundtrip.json');await download.saveAs(file);const exported=JSON.parse(await fs.readFile(file,'utf8'));assert.match(exported.project.id,/^gamma-feature-test-/);assert.equal(!!exported.project.sets.find(x=>x.id==='ft-set-bar-counter').locked,!initialLock);
  const importedFixture=structuredClone(exported);importedFixture.project.id='gamma-feature-test-regression-roundtrip';const importFile=path.join(outputDir,'fixture-roundtrip-import.json');await fs.writeFile(importFile,JSON.stringify(importedFixture));
  await page.locator('#stage-import-json').setInputFiles(importFile);await page.locator('#stage-import-replace').waitFor({state:'visible'});await h.assertFixture(page);await page.locator('#stage-import-replace').click();await page.waitForFunction(()=>document.getElementById('stage-import-modal').hidden);const imported=await h.assertFixture(page);assert.equal(!!imported.sets.find(x=>x.id==='ft-set-bar-counter').locked,!initialLock);assert.deepEqual(imported.scenes.find(x=>x.id==='ft-scene-c1').pieces,exported.project.scenes.find(x=>x.id==='ft-scene-c1').pieces,'C-1 pieces must roundtrip unchanged');await h.reloadFixture(page);assert.equal(!!(await h.assertFixture(page)).sets.find(x=>x.id==='ft-set-bar-counter').locked,!initialLock);
  return{scene:'C-1',projectId:imported.id,changedControl:'stage-piece-lock',locked:!initialLock,exportFile:file,importFile,exportTransport:'browser-download (OS save picker excluded)',pieceCount:exported.project.scenes.find(x=>x.id==='ft-scene-c1').pieces.length};
}
async function sameIdImport({page,outputDir}) {
  assert(outputDir,'Runner must supply outputDir');await h.assertFixture(page);await page.evaluate(()=>{window.showSaveFilePicker=undefined;});await page.locator('#stage-export-json').scrollIntoViewIfNeeded();await page.locator('#stage-export-json').click();const pending=page.waitForEvent('download');await page.locator('#stage-project-export-form button[type=submit]').click();if(await page.locator('#stage-venue-export-include').isVisible())await page.locator('#stage-venue-export-include').click();const download=await pending;await fs.mkdir(outputDir,{recursive:true});const file=path.join(outputDir,'fixture-same-id.json');await download.saveAs(file);const exported=JSON.parse(await fs.readFile(file,'utf8'));assert.match(exported.project.id,/^gamma-feature-test-/);
  await h.assertFixture(page);await page.locator('#stage-import-json').setInputFiles(file);await page.locator('#stage-import-replace').waitFor({state:'visible'});await h.assertFixture(page);await page.locator('#stage-import-replace').click();await page.locator('#stage-import-modal').waitFor({state:'hidden'});
  // Import may intentionally create a copy ID. Only read after this boundary;
  // the imported bytes are the fixture export from this fresh context.
  const actual=(await h.documentValue(page)).project;assert(actual.scenes.every(x=>typeof x.id==='string'&&x.id.startsWith('ft-')),'Imported show must contain only fixture scene IDs');assert.deepEqual(actual.scenes.map(x=>x.id),exported.project.scenes.map(x=>x.id));assert.equal(actual.title,exported.project.title);assert.deepEqual(actual.scenes.find(x=>x.id==='ft-scene-c1').pieces,exported.project.scenes.find(x=>x.id==='ft-scene-c1').pieces);assert.equal(!!actual.sets.find(x=>x.id==='ft-set-bar-counter').locked,!!exported.project.sets.find(x=>x.id==='ft-set-bar-counter').locked);await page.waitForTimeout(1700);const preserved=await page.evaluate(async id=>{const shelf=JSON.parse(localStorage.getItem(SHOSAI_GAMMA_STORAGE_KEYS.showShelf)||'{}');if(shelf[id]?.state)return shelf[id];const backup=await window.SHOSAI_STAGE_PROJECT_BACKUP_STORE?.get(id);return backup?.serializedState?{state:JSON.parse(backup.serializedState),recovery:'IndexedDB backup'}:null;},exported.project.id);if(actual.id!==exported.project.id){assert(preserved?.state?.project,'Original fixture must remain on the show shelf');assert.equal(!!preserved.state.project.sets.find(x=>x.id==='ft-set-bar-counter').locked,!!exported.project.sets.find(x=>x.id==='ft-set-bar-counter').locked);await fs.writeFile(path.join(outputDir,'original-fixture-shelf.json'),JSON.stringify(preserved,null,2));}
  return {scene:'C-1',originalPreserved:actual.id===exported.project.id||!!preserved,sourceId:exported.project.id,importedId:actual.id,exportFile:file,readOnlyAfterImport:true,exportTransport:'browser-download (OS save picker excluded)'};
}
async function audioEntry({page}) {
  await h.assertFixture(page);await page.locator('#stage-panels-toggle').click();const row=page.locator('.stage-panel-visibility-item').filter({hasText:/音楽|Music/i});await row.locator('input').check();await page.locator('#stage-panels-toggle').click();
  const panel=page.locator('[data-panel="music"]');await panel.waitFor({state:'visible'});const control=await h.reachable(page,'.stage-music-import');const picker=page.waitForEvent('filechooser');await page.locator('.stage-music-import').click();const chooser=await picker;assert.equal(await chooser.element().getAttribute('id'),'stage-music-file','Music entry must open its file picker');const project=await h.assertFixture(page);return{scene:'C-1',control,filePicker:'stage-music-file',projectId:project.id};
}
async function workspaceTabs({page}) {
  const original=await h.assertFixture(page),checks=[];
  for(const [id,mode,selector] of [['gamma-script','script','#gamma-script-workspace'],['gamma-cuesheet','cuesheet','#gamma-cuesheet-workspace'],['stage-freecam-open','3d','#stage-fpv-view']]){
    await page.locator('#'+id).click();await page.locator(selector).waitFor({state:'visible'});assert.equal(await page.locator('#'+id).getAttribute('aria-pressed'),'true');assert.equal((await h.assertFixture(page)).id,original.id);checks.push({mode,visible:selector});await page.locator('#stage-workspace-normal').click();await page.locator('#stage-plan-canvas').waitFor({state:'visible'});
  }
  await h.selectPlan(page,'ft-scene-c1','ft-set-bar-counter');await h.inspector(page);return{scene:'C-1',checks,returnedSelection:true};
}
async function cuesNavigation({page}) {
  await h.scene(page,'ft-scene-c1');const initial=await h.assertFixture(page);const scenes=initial.scenes.filter(x=>x.kind==='scene'),index=scenes.findIndex(x=>x.id==='ft-scene-c1');assert(index>=0&&index<scenes.length-1,'C-1 next fixture missing');await h.reachable(page,'#stage-scene-next');await page.locator('#stage-scene-next').click();await h.settle(page);assert.equal((await h.assertFixture(page)).activeSceneId,scenes[index+1].id,'Next UI must advance one scene');await page.locator('#stage-scene-prev').click();await h.settle(page);assert.equal((await h.assertFixture(page)).activeSceneId,'ft-scene-c1','Previous UI must return C-1');return{scene:'C-1',nextScene:scenes[index+1].id,returned:true};
}
const cases={'selection.plan':({page})=>selection(page,'plan'),'selection.front':({page})=>selection(page,'front'),'lanes.left':({page})=>laneCase(page,'left'),'lanes.right':({page})=>laneCase(page,'right'),'lanes.third':({page})=>laneCase(page,'right2'),'storage.roundtrip':storageRoundtrip,'storage.same-id':sameIdImport,'audio.entry':audioEntry,'workspace.tabs':workspaceTabs,'cues.navigation':cuesNavigation};
const catalog=Object.keys(cases).map(id=>({id,title:id,scene:id.startsWith('selection.')?'A-5 / C-1':'C-1',steps:id.startsWith('selection.')?'Canvas select performer and bar; floating ON/OFF; layouts 2/3/left/right':id.startsWith('lanes.')?'Pointer resize; keyboard resize; reload; Enter reset':id==='storage.roundtrip'?'Lock bar; reload; UI JSON export/import; reload':id==='storage.same-id'?'Export original fixture ID; import exact bytes; verify copied content and preserved original':id==='audio.entry'?'Show Music panel; click import file picker':id==='workspace.tabs'?'Open Script, Q sheet, 3D; return Stage; select bar':'Next scene; previous scene',expected:id.startsWith('selection.')?'Correct selected name, inspector visible and pointer reachable; lock control reachable':id.startsWith('lanes.')?'Actual host width changes and persists':'Actual UI outcome matches fixture document'}));
module.exports={cases,catalog,boot:h.boot};
