'use strict';
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const hash = x => crypto.createHash('sha256').update(x).digest('hex');
const esc = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fingerprint(root) {
  const names = execFileSync('git',['ls-files','-z'],{cwd:root}).toString().split('\0').filter(Boolean)
    .filter(n=>!n.startsWith('tests/') && /\.(js|css|html|json|webmanifest)$/.test(n));
  const files=names.sort().map(name=>({name,sha256:hash(fs.readFileSync(path.join(root,name)))}));
  return {sha256:hash(JSON.stringify(files)),files};
}
function summary(results) {
  const counts={pass:0,fail:0,blocked:0,manual:0,na:0};
  for(const r of results){if(!Object.hasOwn(counts,r.status))throw Error('Unknown result status: '+r.status);counts[r.status]++;}
  return {...counts,exitCode:counts.fail?1:counts.blocked||!counts.pass?2:0};
}
function validateResult(r) {
  if(r.schema!==1||r.kind!=='gamma-regression-run'||!r.runId||!r.source?.sha256||!Array.isArray(r.results)||!r.results.length)throw Error('Invalid regression result');
  const keys=new Set();
  for(const row of r.results){const k=[row.id,row.engine,row.viewport].join(':');if(keys.has(k))throw Error('Duplicate check '+k);keys.add(k);if(!row.id||!row.title||!row.status)throw Error('Incomplete check');if(['fail','blocked','na'].includes(row.status)&&!row.reason)throw Error('Reason required');}
  summary(r.results);return r;
}
function render(r) {
  validateResult(r);const s=summary(r.results);
  const labels={pass:'自動で確認済み',fail:'不具合を検出',blocked:'実行できず',manual:'人の確認が必要',na:'この条件では対象外'};
  const rows=r.results.map((c,i)=>`<tr data-status="${esc(c.status)}"><td><label class="check-target"><input type="checkbox" ${c.status==='pass'?'checked':''} ${c.status==='manual'?'data-manual="'+i+'"':'disabled'} aria-label="${esc(c.title)}の確認"></label></td><td><strong>${esc(c.title)}</strong><div class="sub">${esc(c.id)} · ${esc(c.scene||'—')}</div><details><summary>手順と結果</summary><p>${esc(c.steps||'')}</p><p>${esc(c.expected||'')}</p><pre>${esc(c.reason||JSON.stringify(c.details||{},null,2))}</pre></details></td><td><span class="status ${esc(c.status)}">${labels[c.status]}</span><div class="sub">${esc(c.engine||'実機')} ${esc(c.viewport||'')}</div></td><td>${c.screenshot?`<a href="${esc(c.screenshot)}">画面</a>`:'—'}</td></tr>`).join('');
  const data=JSON.stringify({runId:r.runId,source:r.source.sha256}).replace(/</g,'\\u003c');
  return `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>γ 更新チェック ${esc(r.version)}</title><style>
:root{--paper:#f6f2e8;--ink:#242c32;--muted:#525b62;--line:#bdc2c4;--ok:#17653e;--bad:#a12628;--warning:#754800;--space:16px;--body:16px;--small:14px;--radius:4px}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:var(--body)/1.65 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:32px 20px}h1{font-size:28px;margin:0 0 12px}h2{font-size:21px}p{max-width:78ch}.sub{font-size:var(--small);color:var(--muted)}.banner{border-left:6px solid ${s.fail?'var(--bad)':s.blocked?'var(--warning)':'var(--ok)'};padding:12px 18px;background:white;margin:20px 0}.tools{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:20px 0}button,select,input[type=search]{font:inherit;min-height:44px;padding:8px 12px;background:white;border:1px solid var(--muted);border-radius:var(--radius)}input[type=checkbox]{width:22px;height:22px;accent-color:var(--ok)}button{cursor:pointer}table{border-collapse:collapse;width:100%;min-width:650px;background:#fff}td,th{text-align:left;padding:12px 10px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:var(--small)}td:first-child{width:62px}.check-target{display:flex;align-items:center;justify-content:center;min-width:44px;min-height:44px}td:nth-child(3){width:195px}a{color:#18567e;text-underline-offset:3px}.tools>a,td:last-child>a{display:inline-flex;align-items:center;justify-content:center;min-width:44px;min-height:44px;white-space:nowrap}a:focus,button:focus,input:focus,select:focus,summary:focus{outline:3px solid #946000;outline-offset:2px}summary{min-height:44px;cursor:pointer;padding:8px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-width:70ch;font-size:13px}.pass{color:var(--ok)}.fail{color:var(--bad)}.blocked,.manual{color:var(--warning)}.status{font-weight:700}textarea{width:100%;min-height:120px;font:inherit;padding:12px}footer{margin-top:24px}.table-wrap{overflow:auto}@media(max-width:650px){main{padding:20px 12px}h1{font-size:24px}td,th{padding:10px 6px}td:nth-child(3){width:135px}.sub{overflow-wrap:anywhere}.table-wrap{font-size:14px}}@media print{.tools,button{display:none}main{max-width:none;padding:0}details{display:block}}
</style><main><p class="sub">舞台スケッチγ ／ 更新前・定期の確認帳</p><h1>${esc(r.version)} の動作チェック</h1><p>同梱の試験場で、選択・ドラッグ・保存を実際に操作した結果です。自動結果は編集できません。実機で確かめる欄のチェックとメモは、この結果専用に手元へ保存できます。</p><div class="banner"><strong>自動確認 ${s.pass}件合格 ／ ${s.fail}件失敗 ／ ${s.blocked}件未実行</strong><br>手動確認 ${s.manual}件・対象外 ${s.na}件。自動テストの合格は、全機能・実機・公開承認の完了を意味しません。${r.inject?'<br><strong>故障注入の試験結果です。正常版の検証結果として使えません。</strong>':''}</div><p class="sub">実行 ${esc(r.startedAt)}<br>コミット ${esc(r.commit)}${r.dirty?'（未コミット変更を含む）':''}<br>実行ID ${esc(r.runId)}<br>配信元 ${esc(r.baseURL)}<br>内容の識別値 ${esc(r.source.sha256)}</p><div class="tools"><label>表示 <select id="filter"><option value="all">すべて</option><option value="fail">不具合</option><option value="blocked">未実行</option><option value="manual">人の確認</option><option value="pass">自動で確認済み</option></select></label><button id="export">確認メモをJSONで保存</button><a href="result.json">機械判定の記録</a></div><div class="table-wrap"><table><thead><tr><th>確認</th><th>項目・試す場面</th><th>判定・環境</th><th>証拠</th></tr></thead><tbody>${rows}</tbody></table></div><h2>この版の確認メモ</h2><p class="sub">チェックだけでは自動判定を書き換えません。実機名・操作・結果を併記してください。次の実行へチェックを自動で引き継ぎません。</p><textarea id="memo" aria-label="確認メモ"></textarea><p id="save-state" role="status"></p><footer class="sub">既存の詳細確認帳938項目は補助資料です。この自動チェックの対象数とは別に管理します。</footer></main><script>
const meta=${data},key='gamma-regression-review:'+meta.source+':'+meta.runId;const box=document.querySelector('#memo'),status=document.querySelector('#save-state');let saved={checks:{},memo:''};try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&typeof s.memo==='string'&&s.checks&&typeof s.checks==='object')saved=s}catch(e){status.textContent='保存済みメモを読めません。JSON保存を使ってください。'}box.value=saved.memo;for(const el of document.querySelectorAll('[data-manual]')){el.checked=saved.checks[el.dataset.manual]===true;el.addEventListener('change',save)}box.addEventListener('input',save);function save(){saved={checks:{},memo:box.value};for(const el of document.querySelectorAll('[data-manual]'))saved.checks[el.dataset.manual]=el.checked;try{localStorage.setItem(key,JSON.stringify(saved));status.textContent='この実行の確認メモを保存しました。'}catch(e){status.textContent='端末へ保存できません。JSONで保存してください。'}}document.querySelector('#filter').onchange=e=>{for(const row of document.querySelectorAll('tbody tr'))row.hidden=e.target.value!=='all'&&row.dataset.status!==e.target.value};document.querySelector('#export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({kind:'gamma-regression-human-review',schema:1,...meta,...saved,at:new Date().toISOString()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='gamma-review-'+meta.runId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
</script></html>`;
}
module.exports={hash,esc,fingerprint,summary,validateResult,render};
